image: gitpod/workspace-postgres

tasks:
  - init: npm i
    command: npm run dev
vscode:
  extensions:
    - svelte.svelte-vscode
ports:
  - port: 5173
    onOpen: open-browser
  - port: 5432
    onOpen: ignore